---
repos:
  - repo: https://github.com/ansible-network/collection_prep
    rev: 1.1.2
    hooks:
      - id: update-docs

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      # - id: no-commit-to-branch
      - id: trailing-whitespace

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v4.0.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/tombi-toml/tombi-pre-commit
    rev: v0.6.38
    hooks:
      - id: tombi-format
      - id: tombi-lint

  - repo: https://github.com/biomejs/pre-commit
    rev: "v2.2.7"
    hooks:
      - id: biome-ci
        additional_dependencies: ["@biomejs/biome@2.1.1"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff-check
      - id: ruff-format

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
        types: [file, yaml]
        entry: yamllint --strict

  - repo: https://github.com/ansible/ansible-lint
    rev: v25.9.2
    hooks:
      - id: ansible-lint
