---
- name: Distcc!
  hosts: raspberry
  user: root
  tasks:
  - name: Install distcc
    pacman: name=distcc, state=installed
  - name: Unblock distcc
    lineinfile: dest=/etc/makepkg.conf backrefs=yes
                regexp='^BUILDENV=\(([ !\w]*) (?:!)?distcc ([ !\w]*)\)'
                line='BUILDENV=(\1 distcc \2)'
  - name: Set up distcc hosts
    lineinfile: dest=/etc/makepkg.conf regexp='^(#)?DISTCC_HOSTS'
        line='DISTCC_HOSTS="chibi-moon moonlight-knight pluto celestia"'
  - name: Set MAKEFLAGS
    lineinfile: dest=/etc/makepkg.conf regexp='^(#)?MAKEFLAGS'
                line='MAKEFLAGS="-j4"'
  - name: Set distcc arguments
    lineinfile: dest=/etc/conf.d/distccd regexp=DISTCC_ARGS
                line='DISTCC_ARGS="--user nobody --allow 192.168.1.0/24"'
  - name: Enable & start distccd
    service: name=distccd state=started enabled=yes
