---
- name: Run base role on all hosts
  import_playbook: base.yml

- name: Handle Raspberry Pi hosts
  import_playbook: raspberry.yml

- name: Provision workstations
  hosts: workstation
  remote_user: kate
  roles:
    - workstation
