---
- name: Run base role on all hosts
  hosts: all
  roles:
    - base
  tags: base

- name: Handle Raspberry Pi hosts
  import_playbook: raspberry.yml
  tags: raspberry

- name: Set up desktop environment
  hosts: desktop
  roles:
    - desktop
  tags: desktop

- name: Set up laptop-specific tweaks
  hosts: laptop
  roles:
    - laptop
  tags: laptop

- name: Set up personal touches
  hosts: personal
  roles:
    - personal
  tags: personal

- name: Set up work environment
  hosts: work
  roles:
    - work
  tags: work
