---
- name: Run base role on all hosts
  import_playbook: base.yml
  tags: base

- name: Handle Raspberry Pi hosts
  import_playbook: raspberry.yml
  tags: raspberry

- name: Set up desktop environment
  hosts: desktop
  roles:
    - desktop
  tags: desktop
