---
- hosts: raspberry
  remote_user: nate
  sudo: yes
  roles:
    - base_raspi

- hosts: media
  remote_user: nate
  sudo: yes
  roles:
    - media

- hosts: pitop
  remote_user: nate
  sudo: yes
  roles:
    - desktop

- hosts: retro
  remote_user: nate
  sudo: yes
  roles:
    - retro
