---
- hosts: raspberry
  remote_user: nate
  become: yes
  roles:
    - base_raspi

- hosts: media
  remote_user: nate
  become: yes
  roles:
    - media
    - distcc

- hosts: pitop
  remote_user: nate
  become: yes
  roles:
    - desktop

- hosts: retro
  remote_user: nate
  become: yes
  roles:
    - retro
    - distcc

- hosts: workstation
  remote_user: nate
  become: yes
  roles:
    - workstation
