---
- hosts: raspberry
  remote_user: nate
  become: yes
  roles:
    - raspberry

- hosts: media
  remote_user: nate
  become: yes
  roles:
    - media

- hosts: pitop
  remote_user: nate
  roles:
    - desktop

- hosts: retro
  remote_user: nate
  become: yes
  roles:
    - retro
