---
- name: Install X
  become: yes
  package:
      name: xorg,xorg-xinit,xorg-xmodmap,xterm,lightdm-gtk-greeter,accountsservice
      state: installed
  when: ansible_os_family == 'Archlinux'

- name: Install copr repos
  become: yes
  yum_repository:
      name: "{{ item.owner }}-{{ item.repo }}"
      description: Copr repo for {{ item.repo }} owned by {{ item.owner }}
      baseurl: https://copr-be.cloud.fedoraproject.org/results/{{ item.owner }}/{{ item.repo }}/fedora-$releasever-$basearch/
      gpgkey: https://copr-be.cloud.fedoraproject.org/results/{{ item.owner }}/{{ item.repo }}/pubkey.gpg
      gpgcheck: yes
      file: _copr_{{ item.owner }}-{{ item.repo }}
  with_items:
    - {owner: yaroslav, repo: i3desktop}
    - {owner: numix, repo: numix}
    - {owner: notkild, repo: pamixer}
    - {owner: dirkdavidis, repo: papirus-icon-theme}
  when: ansible_distribution == 'Fedora'

- name: Set up user avatar
  become: yes
  copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
  with_items:
      - { src: avatar.png, dest: /var/lib/AccountsService/icons/nate }
      - { src: user_file, dest: /var/lib/AccountsService/users/nate }

- name: Install desktop applications & themes
  become: yes
  package:
      name: herbstluftwm,compton,dzen2,rofi,conky,nitrogen,lilyterm,thunar,dunst,numix-gtk-theme,papirus-icon-theme
      state: installed

- name: Copy base dotfiles
  copy:
      src: "{{ item }}"
      dest: "~/.{{ item }}"
  with_items:
      - gtkrc-2.0
      - stalonetrayrc
      - xmodmap
      - xscreensaver

- name: Copy .config directory
  copy:
      src: config/{{ item.path }}
      dest: ~/.config/{{ item.path }}
  with_filetree: config/
  when: item.state == 'file'

- name: Dzen conkyrc template
  template:
      src: conkyrc.j2
      dest: ~/.config/herbstluftwm/conkyrc

- name: Copy helper scripts
  copy:
      src: "{{ item }}"
      dest: ~/bin/
  with_fileglob:
      - bin/*

- name: Make sure xf86-video-odroid-c1 is not present
  become: yes
  package:
      name: xf86-video-odroid-c1
      state: absent
  when: ansible_machine[:3] == 'arm'
