---
- name: Install desktop on Arch
  ansible.builtin.package:
    name:
      - kanshi
      - kitty
      - nemo
      - engrampa
      - imv
      - xed
      - xreader
      - otf-font-awesome
      - papirus-icon-theme
      - ttf-fira-code
      - sddm
      - sway
      - swaybg
      - swayidle
      - swaylock
      - swaync
      - waybar
      - rofi
      - xdg-desktop-portal-gtk
      - xdg-desktop-portal-wlr
      - xdg-user-dirs
      - polkit-gnome
      - grim
      - slurp
    state: installed
  become: true
  when: ansible_os_family == "Archlinux"

- name: Install desktop on Red Hat
  ansible.builtin.package:
    name:
      - lightdm-gtk
      - mozilla-fira-mono-fonts
    state: installed
  become: true
  when: ansible_os_family == "RedHat" and ansible_pkg_mgr != "atomic_container"

- name: Install copr repos
  ansible.builtin.yum_repository:
    name: "{{ item.owner }}-{{ item.repo }}"
    description: Copr repo for {{ item.repo }} owned by {{ item.owner }}
    baseurl: https://copr-be.cloud.fedoraproject.org/results/{{ item.owner }}/{{ item.repo }}/fedora-$releasever-$basearch/
    gpgkey: https://copr-be.cloud.fedoraproject.org/results/{{ item.owner }}/{{ item.repo }}/pubkey.gpg
    gpgcheck: true
    file: _copr_{{ item.owner }}-{{ item.repo }}
  become: true
  loop:
    - { owner: yaroslav, repo: i3desktop }
    - { owner: dirkdavidis, repo: papirus-icon-theme }
    - { owner: oleastre, repo: kitty-terminal }
  when: ansible_distribution == 'Fedora' and ansible_pkg_mgr != "atomic_container"

- name: Ensure accountservice path exists
  ansible.builtin.file:
    path: /var/lib/AccountsService/icons
    mode: ug=rwx,o=rx
    state: directory

- name: Set up user avatar
  ansible.builtin.copy:
    src: avatar.png
    dest: "/var/lib/AccountsService/icons/{{ ansible_user }}"
    mode: u=rw,g=r,o=r
  become: true

- name: Create user directories
  ansible.builtin.file:
    path: "~/{{ item }}"
    mode: u=rwX,g=rX,o=rX
    state: directory
  loop:
    - files/desktop
    - files/documents
    - files/downloads
    - media/music
    - media/pictures
    - media/videos

- name: Create .config directory tree
  ansible.builtin.file:
    path: ~/.config/{{ item.path }}
    mode: u=rwx,g=rx,o=rx
    state: directory
  loop: "{{ query('filetree', 'config/') }}"
  when: item.state == 'directory'
  tags:
    - dotfiles

- name: Copy .config directory
  ansible.builtin.copy:
    src: config/{{ item.path }}
    dest: ~/.config/{{ item.path }}
    mode: u=rw,g=r,o=r
  loop: "{{ query('filetree', 'config/') }}"
  when: item.state == 'file'
  tags:
    - dotfiles

- name: Copy helper scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: ~/.local/bin/
    mode: preserve
  loop: "{{ query('fileglob', 'bin/*') }}"

- name: Make sure xf86-video-odroid-c1 is not present
  become: true
  ansible.builtin.package:
    name: xf86-video-odroid-c1
    state: absent
  when: ansible_machine[:3] == 'arm'

- name: Ensure user services dir exists
  ansible.builtin.file:
    path: ~/.config/systemd/user/
    mode: u=rwx,g=rx,o=rx
    state: directory

- name: Install user services
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: ~/.config/systemd/user/
    mode: preserve
  loop: "{{ query('fileglob', 'services/*') }}"
  notify: Reload systemd

- name: Ensure services are available
  ansible.builtin.meta: flush_handlers

- name: Enable services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    scope: user
  loop:
    - borgmatic.timer
    - kanshi.service
    - sway-xdg-autostart.target
