---
- name: Install X
  become: yes
  package:
      name: xorg,xorg-xinit,xorg-xmodmap,xterm,lightdm-gtk-greeter,accountsservice
      state: installed
  when: ansible_os_family == 'Archlinux'
- name: Set up user avatar
  become: yes
  copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
  with_items:
      - { src: avatar.png, dest: /var/lib/AccountsService/icons/nate }
      - { src: user_file, dest: /var/lib/AccountsService/users/nate }

- name: Install desktop applications
  become: yes
  package:
      name: herbstluftwm,dzen2,rofi,conky,feh,lilyterm
      state: installed
- name: Install themes
  become: yes
  package:
      name: numix-themes,elementary-icon-theme,ttf-symbola
      state: installed
  when: ansible_os_family == 'Archlinux'

- name: Copy base dotfiles
  copy:
      src: "{{ item }}"
      dest: "~/.{{ item }}"
  with_items:
      - gtkrc-2.0
      - xmodmap
      - xscreensaver

- name: Copy herbstluftwm .configs
  copy:
      src: "{{ item }}"
      dest: ~/.config/herbstluftwm
  with_fileglob:
      - config/herbstluftwm/*
- name: Dzen conkyrc template
  template:
      src: conkyrc.j2
      dest: ~/.config/herbstluftwm/conkyrc

- name: Copy lilyterm .configs
  copy:
      src: "{{ item }}"
      dest: ~/.config/lilyterm
  with_fileglob:
      - config/lilyterm/*

- name: Copy gtk .configs
  copy:
      src: config/gtk-3.0/settings.ini
      dest: ~/.config/gtk-3.0

- name: Copy helper scripts
  copy:
      src: "{{ item }}"
      dest: ~/bin/
  with_fileglob:
      - bin/*

- name: Make sure xf86-video-odroid-c1 is not present
  become: yes
  package:
      name: xf86-video-odroid-c1
      state: absent
  when: ansible_machine[:3] == 'arm'
