---
- name: Distro-specific tasks
  include: "{{ ansible_os_family }}.yaml"

- name: Install common X
  package:
    name:
      - xterm
      - accountsservice
      - xscreensaver
  become: true

- name: Set up user avatar
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: true
  loop:
    - src: avatar.png
      dest: /var/lib/AccountsService/icons/nate
    - src: user_file
      dest: /var/lib/AccountsService/users/nate

- name: Install desktop applications & themes
  package:
    name:
      - herbstluftwm
      - picom
      - dzen2
      - rofi
      - conky
      - nitrogen
      - kitty
      - thunar
      - dunst
      - numix-gtk-theme
      - papirus-icon-theme
      - redshift
      - geoclue
      - stalonetray
    state: installed
  become: true

- name: Manage systemd user services
  systemd:
    user: true
    enabled: true
    state: started
    name: "{{ item }}"
  loop:
    - redshift.service

- name: Copy base dotfiles
  copy:
    src: "{{ item }}"
    dest: "~/.{{ item }}"
  loop:
    - gtkrc-2.0
    - stalonetrayrc
    - xmodmap
    - xscreensaver
  tags:
    - dotfiles

- name: Create .config directory tree
  file:
    path: ~/.config/{{ item.path }}
    state: directory
  loop: "{{ query('filetree', 'config/') }}"
  when: item.state == 'directory'

- name: Copy .config directory
  copy:
    src: config/{{ item.path }}
    dest: ~/.config/{{ item.path }}
  loop: "{{ query('filetree', 'config/') }}"
  when: item.state == 'file'
  tags:
    - dotfiles

- name: Copy panel xbm icons
  copy:
    src: "{{ item }}"
    dest: ~/.local/share/icons/
  loop: "{{ query('fileglob', 'local/share/icons/*') }}"

- name: Dzen conkyrc template
  template:
    src: conkyrc.j2
    dest: ~/.config/herbstluftwm/conkyrc
  tags:
    - dotfiles

- name: Copy helper scripts
  copy:
    src: "{{ item }}"
    dest: ~/bin/
  loop: "{{ query('fileglob', 'bin/*') }}"

- name: Make sure xf86-video-odroid-c1 is not present
  become: true
  package:
    name: xf86-video-odroid-c1
    state: absent
  when: ansible_machine[:3] == 'arm'
