---
- name: Install desktop on Arch
  ansible.builtin.package:
    name:
      - kanshi
      - kitty
      - mako
      - nemo
      - numix-gtk-theme
      - otf-font-awesome
      - papirus-icon-theme
      - sddm
      - sway
      - ttf-fira-code
      - waybar
      - wofi
    state: installed
  become: true
  when: ansible_os_family == "ArchLinux"

- name: Install X on Red Hat
  ansible.builtin.package:
    name:
      - lightdm-gtk
      - mozilla-fira-mono-fonts
    state: installed
  become: true
  when: ansible_os_family == "RedHat"

- name: Install copr repos
  ansible.builtin.yum_repository:
    name: "{{ item.owner }}-{{ item.repo }}"
    description: Copr repo for {{ item.repo }} owned by {{ item.owner }}
    baseurl: https://copr-be.cloud.fedoraproject.org/results/{{ item.owner }}/{{ item.repo }}/fedora-$releasever-$basearch/
    gpgkey: https://copr-be.cloud.fedoraproject.org/results/{{ item.owner }}/{{ item.repo }}/pubkey.gpg
    gpgcheck: true
    file: _copr_{{ item.owner }}-{{ item.repo }}
  become: true
  loop:
    - {owner: yaroslav, repo: i3desktop}
    - {owner: dirkdavidis, repo: papirus-icon-theme}
    - {owner: oleastre, repo: kitty-terminal}
  when: ansible_distribution == 'Fedora'

- name: Set up user avatar
  ansible.builtin.copy:
    src: avatar.png
    dest: "/var/lib/AccountsService/icons/{{ ansible_user }}"
    mode: u=rw,g=r,o=r
  become: true

- name: Create .config directory tree
  ansible.builtin.file:
    path: ~/.config/{{ item.path }}
    mode: u=rwx,g=rx,o=rx
    state: directory
  loop: "{{ query('filetree', 'config/') }}"
  when: item.state == 'directory'
  tags:
    - dotfiles

- name: Copy .config directory
  ansible.builtin.copy:
    src: config/{{ item.path }}
    dest: ~/.config/{{ item.path }}
    mode: u=rw,g=r,o=r
  loop: "{{ query('filetree', 'config/') }}"
  when: item.state == 'file'
  tags:
    - dotfiles

- name: Copy helper scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: ~/bin/
    mode: preserve
  loop: "{{ query('fileglob', 'bin/*') }}"

- name: Make sure xf86-video-odroid-c1 is not present
  become: true
  ansible.builtin.package:
    name: xf86-video-odroid-c1
    state: absent
  when: ansible_machine[:3] == 'arm'
