---
desktop_packages:
  common:
    - kanshi
    - sddm
    - sway
    - swaybg
    - swayidle
    - swaylock
    - waybar
    - rofi-wayland
    - rofimoji
    - xdg-desktop-portal-gtk
    - xdg-desktop-portal-wlr
    - xdg-user-dirs
    - grim
    - slurp
    - network-manager-applet
    - polkit-gnome
    # Theming
    - papirus-icon-theme
    # Applications
    - engrampa
    - firefox
    - flatpak
    - imv
    - kitty
    - mpv
    - thunar
    - xed
    - xreader
  Archlinux:
    - swaync
    # Fonts
    - otf-font-awesome
    - ttf-fira-code
    - ttf-roboto-mono
    - noto-fonts-cjk
    - noto-fonts-emoji
  RedHat:
    # Fonts
    - fira-code-fonts
    - fontawesome-fonts-all
    - google-noto-fonts
    - google-roboto-mono-fonts
    # Required for waypaper
    - cairo-gobject-devel
    - python-devel
