---
- name: Install general development tools
  become: yes
  package: name=base-devel,hub,python-pylint,vim-syntastic state=installed
  when: ansible_os_family == 'Archlinux'
- name: Install general development tools
  become: yes
  package: name=alsa-utils,rsync,pluma state=installed
- name: Install Python development tools
  become: yes
  package: name=python-virtualenvwrapper state=installed

- name: Install general programs
  become: yes
  package:
      name=firefox,thunderbird,liferea,audacious,hexchat,pidgin,eom,mpv,atril,engrampa
      state=installed
