---
- name: Install general development tools
  package: name=base-devel,hub,alsa-utils,rsync,pluma state=installed
- name: Install Python development tools
  package: name=python-virtualenvwrapper,python-pylint,vim-syntastic state=installed

- name: Install general programs
  package:
      name=firefox,thunderbird,liferea,audacious,hexchat,pidgin,eom,mpv,atril,engrampa
      state=installed
