---
- name: Install general development tools
  package:
    name: alsa-utils,rsync,pluma
    state: installed
  become: true

- name: Install ArchLinux-flavored development tools
  package:
    name:
      - base-devel
      - hub
    state: installed
  become: true
  when: ansible_os_family == 'Archlinux'

- name: Install Python development tools
  package:
    name: python-virtualenvwrapper
    state: installed
  become: true

- name: Install general programs
  package:
    name:
      - firefox
      - thunderbird
      - audacious
      - hexchat
      - pidgin
      - eom
      - mpv
      - atril
      - engrampa
    state: installed
  become: true
