---
- name: Install ArchLinux-flavored development tools
  ansible.builtin.package:
    name:
      - base-devel
      - github-cli
    state: installed
  become: true
  when: ansible_os_family == 'Archlinux'

- name: Install general programs
  ansible.builtin.package:
    name:
      - rsync
      - firefox
      - thunderbird
      - audacious
      - imv
      - mpv
      - engrampa
      - xed
      - xreader
    state: installed
  become: true
