---
- name: Install ArchLinux-flavored development tools
  ansible.builtin.package:
    name:
      - base-devel
      - hub
      - github-cli
    state: installed
  become: true
  when: ansible_os_family == 'Archlinux'

- name: Install general programs
  ansible.builtin.package:
    name:
      - rsync
      - pluma
      - firefox
      - thunderbird
      - audacious
      - eom
      - mpv
      - atril
      - engrampa
    state: installed
  become: true
