---
- name: Install general development tools
  package:
    name: alsa-utils,rsync,pluma
    state: installed
  become: yes

- name: Install ArchLinux-flavored development tools
  package:
    name: base-devel,hub,python-pylint
    state: installed
  become: yes
  when: ansible_os_family == 'Archlinux'

- name: Install Red Hat-flavored development tools
  package:
    name: pylint
    state: installed
  become: yes
  when: ansible_os_family == 'RedHat'

- name: Install Python development tools
  package:
    name: python-virtualenvwrapper
    state: installed
  become: yes

- name: Install general programs
  become: yes
  package:
    name: firefox,thunderbird,audacious,hexchat,pidgin,eom,mpv,atril,engrampa
    state: installed
