---
- name: Install development tools on Arch Linux
  ansible.builtin.package:
    name:
      - base-devel
      - github-cli
    state: installed
  become: true
  when: ansible_os_family == 'Archlinux'

- name: Install development tools on Red Hat
  ansible.builtin.package:
    name:
      - gh
    state: installed
  become: true
  when: ansible_os_family == "RedHat" and ansible_pkg_mgr != "atomic_container"

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install flatpaks
  community.general.flatpak:
    name:
      - com.github.tchx84.Flatseal
      - hu.irl.cameractrls
      - org.keepassxc.KeePassXC
      - org.mozilla.Thunderbird
      - org.pipewire.Helvum
    method: user
    state: present
