---
- name: Install Arch Linux-flavored development tools
  ansible.builtin.package:
    name:
      - base-devel
      - github-cli
    state: installed
  become: true
  when: ansible_os_family == 'Archlinux'

- name: Install general programs
  ansible.builtin.package:
    name:
      - rsync
      - firefox
      - flatpak
      - imv
      - mpv
      - engrampa
      - xed
      - xreader
    state: installed
  become: true
  when: ansible_pkg_mgr != "atomic_container"

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user


- name: Install flatpaks
  community.general.flatpak:
    name:
      - com.discordapp.Discord
      - com.github.tchx84.Flatseal
      - hu.irl.cameractrls
      - org.atheme.audacious
      - org.keepassxc.KeePassXC
      - org.mozilla.Thunderbird
    method: user
    state: present
