---
- name: Create directory structure
  ansible.builtin.file:
    path: "~/.{{ item }}/{{ dir.path }}"
    mode: u=rwx,g=rx,o=rx
    state: directory
  loop: "{{ query('filetree', item) }}"
  loop_control:
    label: "{{ item }}/{{ dir.path }}"
    loop_var: dir
  when: dir.state == 'directory'

- name: Copy files into destination tree
  ansible.builtin.copy:
    src: "{{ item }}/{{ file.path }}"
    dest: "~/.{{ item }}/{{ file.path }}"
    mode: preserve
  loop: "{{ query('filetree', item) }}"
  loop_control:
    label: "{{ item }}/{{ file.path }}"
    loop_var: file
  when: file.state == 'file'
