---
- name: Get latest release information
  ansible.builtin.uri:
    url: "https://api.github.com/repos/{{ item.repo }}/releases/latest"
  check_mode: false
  register: result

- name: Extract matching release by name
  ansible.builtin.set_fact:
    release_data: "{{ result.json.assets | selectattr('name', 'match', '^(' ~ (item.match | default('.*')) ~ ')$') | first }}"
    dest_path: "{{ item.dest | default('~/.local/bin') }}/{{ item.repo | split('/') | last }}"

- name: Download file to dest
  ansible.builtin.get_url:
    url: "{{ release_data.browser_download_url }}"
    dest: "{{ dest_path }}"
    checksum: "{{ release_data.digest }}"
    mode: "u=rwx,g=rx,o=rx"
  when: not ansible_check_mode
