# .zshrc is sourced in interactive shells.
# It should contain commands to set up aliases,
# functions, options, key bindings, etc.

autoload -U compinit
compinit

#allow tab completion in the middle of a word
setopt COMPLETE_IN_WORD

## keep background processes at full speed
#setopt NOBGNICE
## restart running processes on exit
#setopt HUP

## history
HISTFILE=~/.zsh/history
HISTSIZE=100000
SAVEHIST=100000
setopt APPEND_HISTORY
setopt histignorealldups
## for sharing history between zsh processes
#setopt INC_APPEND_HISTORY
#setopt SHARE_HISTORY

# No error if glob fails
unsetopt NOMATCH
# Turn off flow control (^S/^Q)
unsetopt FLOW_CONTROL
stty -ixon -ixoff

## never ever beep ever
#setopt NO_BEEP

## automatically decide when to page a list of completions
#LISTMAX=0

## disable mail checking
#MAILCHECK=0

# autoload -U colors
#colors

export EDITOR=vim
# But use emacs-style keys
bindkey -e
#export PIP_REQUIRE_VIRTUALENV=1

# User specific aliases and functions
export PATH="$HOME/bin:$PATH"
source distro_check.sh

# Set up virtualenv & do distro-specific stuff
WORKON_HOME=~/.local/virtualenvs-$DISTRO
if [[ $DISTRO == 'Arch' ]]; then
    source virtualenvwrapper.sh
elif [[ $DISTRO == 'Debian' ]]; then
    source /etc/bash_completion.d/virtualenvwrapper
fi

eval "$(hub alias -s)"
eval "$(fasd --init auto)"
alias j="fasd_cd -d"
alias v="f -e vim"

echo $DISTRO

source /etc/profile
source ~/.zsh/aliases
source ~/.zsh/prompt
if [ $OSTYPE != 'cygwin' ]; then
    source ~/.zsh/keyboard
fi

if hash fortune 2>/dev/null; then
    fortune -ac
fi
