# .zshrc is sourced in interactive shells.
# It should contain commands to set up aliases,
# functions, options, key bindings, etc.

autoload -U compinit
fpath+=~/.zsh/zfunc
compinit

#allow tab completion in the middle of a word
setopt COMPLETE_IN_WORD

## keep background processes at full speed
#setopt NOBGNICE
## restart running processes on exit
#setopt HUP

## history
HISTFILE=~/.zsh/history
HISTSIZE=100000
SAVEHIST=100000
setopt APPEND_HISTORY
setopt histignorealldups
## for sharing history between zsh processes
#setopt INC_APPEND_HISTORY
#setopt SHARE_HISTORY

# No error if glob fails
unsetopt NOMATCH
# Turn off flow control (^S/^Q)
unsetopt FLOW_CONTROL
stty -ixon -ixoff

## never ever beep ever
#setopt NO_BEEP

## automatically decide when to page a list of completions
#LISTMAX=0

## disable mail checking
#MAILCHECK=0

# autoload -U colors
#colors

export PIP_REQUIRE_VIRTUALENV=true
export EDITOR=vim
# But use emacs-style keys
bindkey -e

source distro_check.sh
echo $DISTRO

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"

eval "$(fasd --init auto)"
eval "$(pyenv init -)"
eval "$(hub alias -s)"

source /etc/profile
source ~/.zsh/aliases
source ~/.zsh/prompt
if [ $OSTYPE != 'cygwin' ]; then
    source ~/.zsh/keyboard
fi

if hash fortune 2>/dev/null; then
    fortune -ac
fi
