---
- name: Install distcc
  package: name=distcc state=installed
  notify: Enable distccd

- name: Setup makepkg.conf
  lineinfile:
      dest: /etc/makepkg.conf
      backrefs: yes
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
  with_items:
      - { regexp: '^BUILDENV=\(([ !\w]*) (?:!)?distcc ([ !\w]*)\)', line: 'BUILDENV=(\1 distcc \2)' }
      - { regexp: '^(#)?DISTCC_HOSTS', line: "DISTCC_HOSTS=\"{{ ' '.join(groups['media']) }}\"" }
      - { regexp: '^(#)?MAKEFLAGS', line: "MAKEFLAGS=\"-j{{ groups['media']|length }}\"" }
- name: Set distcc arguments
  lineinfile:
      dest: /etc/conf.d/distccd
      regexp: '^DISTCC_ARGS'
      line: 'DISTCC_ARGS="--user nobody --allow 192.168.1.0/24"'
