---
- name: Install low-battery udev rule
  copy: 
      src: 99-lowbatt.rule 
      dest: /etc/udev/rules.d

- name: Install xbacklight
  package:
    name: xbacklight
  become: yes

- name: Install bluetooth & applet
  package:
    name: blueberry
  become: yes
