---
- name: Install bluetooth & applet
  ansible.builtin.package:
    name: blueman
  become: true
  when: ansible_pkg_mgr != "atomic_container"

- name: Copy udev hibernate rule
  ansible.builtin.copy:
    src: 99-lowbatt.rules
    dest: /etc/udev/rules.d/
    mode: u=rw,g=r,o=r
  become: true

- name: Copy config files
  ansible.builtin.include_tasks: tasks/copy_filetree.yaml
  loop:
    - config
  tags:
    - dotfiles

- name: Template internal kanshi config
  ansible.builtin.template:
    src: internal.j2
    dest: ~/.config/kanshi/internal
    mode: u=rw,g=r,o=r

- name: Set up wireless/ethernet bond
  community.general.nmcli:
    conn_name: bond
    fail_over_mac: active
    ifname: bond0
    miimon: 100
    mode: active-backup
    primary: "{{ laptop_dock_ifname }}"
    state: present
    type: bond
    updelay: 200

- name: Set up wireless subordinate connection
  community.general.nmcli:
    conn_name: bond-wlan
    ifname: "{{ wireless_ifname }}"
    master: bond0
    slave_type: bond
    ssid: "Casa del Caso"
    state: present
    type: wifi
    wifi_sec:
      key-mgmt: wpa-psk

- name: Set up ethernet subordinate connection
  community.general.nmcli:
    conn_name: bond-eth
    ifname: "{{ laptop_dock_ifname }}"
    master: bond0
    slave_type: bond
    state: present
    type: ethernet
