---
- name: Install bluetooth & applet
  ansible.builtin.package:
    name: blueman
  become: true

- name: Copy udev hibernate rule
  ansible.builtin.copy:
    src: 99-lowbatt.rules
    dest: /etc/udev/rules.d/
    mode: u=rw,g=r,o=r
  become: true

- name: Create .config directory tree
  ansible.builtin.file:
    path: ~/.config/{{ item.path }}
    mode: u=rwx,g=rx,o=rx
    state: directory
  loop: "{{ query('filetree', 'config/') }}"
  when: item.state == 'directory'
  tags:
    - dotfiles

- name: Copy .config directory
  ansible.builtin.copy:
    src: config/{{ item.path }}
    dest: ~/.config/{{ item.path }}
    mode: u=rw,g=r,o=r
  loop: "{{ query('filetree', 'config/') }}"
  when: item.state == 'file'
  tags:
    - dotfiles
