---
- name: Install bluetooth & applet
  ansible.builtin.package:
    name: blueberry
  become: true

- name: Set up network bond
  community.general.nmcli:
    type: bond
    conn_name: "dock-bond"
    ifname: bond0
    mode: "active-backup"
    primary: "{{ ethernet }}"
    miimon: 100
    updelay: 200
    downdelay: 0

- name: Assign Ethernet to bond
  community.general.nmcli:
    type: ethernet
    conn_name: "Dock Ethernet"
    ifname: "{{ ethernet }}"
    master: bond0

- name: Assign WiFi to bond
  community.general.nmcli:
    type: wifi
    conn_name: "{{ wifi_name }}"
    ifname: "{{ wifi }}"
    master: bond0
    ssid: "{{ wifi_name }}"
    wifi:
      hidden: true
    wifi_sec:
      key-mgmt: wpa-psk
      psk: "{{ wifi_psk }}"
