---
- name: Install bluetooth & applet
  ansible.builtin.package:
    name: blueman
  become: true
  when: ansible_pkg_mgr != "atomic_container"

- name: Copy udev hibernate rule
  ansible.builtin.copy:
    src: 99-lowbatt.rules
    dest: /etc/udev/rules.d/
    mode: u=rw,g=r,o=r
  become: true

- name: Template dock ethernet persistent name
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/systemd/network/{{ item | splitext | first }}"
    mode: preserve
  loop:
    - 50-dock-ethernet.link.j2
  become: true

- name: Copy config files
  ansible.builtin.include_tasks: tasks/copy_filetree.yaml
  loop:
    - config
  tags:
    - dotfiles

- name: Template kanshi configs
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "~/.config/kanshi/{{ item | splitext | first }}"
    mode: preserve
  loop:
    - internal.j2
    - home_dock.j2

- name: Set up wireless/ethernet bond
  community.general.nmcli:
    conn_name: bond
    fail_over_mac: active
    ifname: bond0
    miimon: 100
    mode: active-backup
    primary: dock0
    state: present
    type: bond
    updelay: 200

- name: Set up wireless subordinate connection
  community.general.nmcli:
    conn_name: bond-wlan
    ifname: "{{ wireless_ifname }}"
    master: bond0
    slave_type: bond
    ssid: "Casa del Caso"
    state: present
    type: wifi
    wifi_sec:
      key-mgmt: wpa-psk

- name: Set up ethernet subordinate connection
  community.general.nmcli:
    conn_name: bond-eth
    ifname: dock0
    master: bond0
    slave_type: bond
    state: present
    type: ethernet
