---
- name: Install low-battery udev rule
  copy:
      src: 99-lowbatt.rule
      dest: /etc/udev/rules.d

- name: Install xbacklight
  package:
    name: xbacklight
  become: true

- name: Install bluetooth & applet
  package:
    name: blueberry
  become: true

- name: Set up network bond
  shell: "{{ item }}"
  loop:
    - nmcli con add type bond con-name dock-bond ifname bond0 mode active-backup primary enp11s0u1 +bond.options "fail_over_mac=none,miimon=100,primary_reselect=always,updelay=200"
    - nmcli connection add type ethernet ifname enp11s0u1 master bond0 con-name "Dock Ethernet"
    - nmcli connection add type wifi ifname wlp61s0 master bond0 ssid "Casa del Caso" con-name "Home"
    - nmcli connection modify Home wifi-sec.key-mgmt wpa-psk
