---
- name: Install bluetooth & applet
  ansible.builtin.package:
    name: blueman
  become: true

- name: Copy udev hibernate rule
  ansible.builtin.copy:
    src: 99-lowbatt.rules
    dest: /etc/udev/rules.d/
    mode: u=rw,g=r,o=r
  become: true

- name: Copy config files
  ansible.builtin.include_tasks: copy_filetree.yaml
  loop:
    - config
  tags:
    - dotfiles
