- name: Install work apps
  community.general.flatpak:
    name:
      - com.bitwarden.desktop
      - com.slack.Slack
    method: user
    state: present

- name: Override shell in sssd
  ansible.builtin.command:
    cmd: sss_override user-add {{ ansible_user }} -s /usr/bin/zsh
  become: true
  register: work_sss_override
  changed_when: '"SSSD needs to be restarted" in work_sss_override'
  notify: Restart sssd

- name: Get current authselect profile
  ansible.builtin.command:
    cmd: authselect current
  changed_when: false
  register: work_authselect

- name: Enable fingerprint auth
  ansible.builtin.command:
    cmd: authselect select sssd with-fingerprint
  become: true
  when: '"with-fingerprint" not in work_authselect.stdout'
  changed_when: true

- name: Set up work directory
  ansible.builtin.file:
    path: ~/workspace/ansible/
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Add mise config for work
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: ~/workspace/ansible/
    mode: preserve
  loop:
    - mise.toml
    - .gitconfig
