---
- name: Install things
  package: name=base-devel,mpd,kodi-rbp
- name: Add mountpoints to /mnt
  file: path=/mnt/{{ item }} state=directory
  with_items:
   - music
   - videos
- name: Add nfs mounts to fstab
  lineinfile: dest=/etc/fstab
      line='locutus:/data/media/{{ item }} /mnt/{{ item }} nfs4 ro,auto,rsize=32768,udp,noatime 0 0'
      regexp='locutus:/data/media/{{ item }}[a-z04/ ]*'
  with_items:
   - music
   - videos
