---
- name: Increase GPU memory split
  lineinfile:
      regexp: 'gpu_mem=*'
      line: 'gpu_mem=192'
      dest: /boot/config.txt

- name: Install media players
  package:
      name: mpd,kodi-rbp
      state: installed
- name: Set up Raspberry hardware decode
  package:
      name: omxplayer-git,xorg-xrefresh,xorg-xset
      state: installed
  when: ansible_machine[:3] == 'arm'

- name: Install retroarch
  package:
      name: libretro
      state: installed

- name: Add nfs mounts to fstab
  mount:
      src: 'locutus:/data/media/{{ item }}'
      name: '/mnt/{{ item }}'
      fstype: nfs4
      state: mounted
  with_items:
   - roms
   - music
   - videos
