#!/bin/bash

# this is a simple config for herbstluftwm

function hc() {
    herbstclient "$@"
}

hc emit_hook reload

#xsetroot -solid '#5A8E3A'
fbsetbg -a -r ~/documents/Dropbox/Pictures/walls/1920

# remove all existing keybindings
hc keyunbind --all
hc set default_frame_layout 3
hc set_layout grid

# keybindings
Mod=Mod1
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Control-Shift-i spawn xcalib -invert -alter

# run lots of things
hc keybind $Mod-Shift-b spawn fbsetbg -a -r ~/documents/Dropbox/Pictures/walls/SFW
hc keybind $Mod-F2 spawn ~/bin/dmenu-frecency
hc keybind $Mod-Shift-F2 spawn dmenu_run
hc keybind $Mod-F3 spawn lilyterm
hc keybind $Mod-F4 spawn xkill
hc keybind $Mod-F5 spawn lilyterm -s -e bpython

hc keybind Mod4-l spawn xscreensaver-command -lock
hc keybind Mod4-o spawn nemo

hc keybind XF86Screensaver spawn xscreensaver-command -lock
hc keybind XF86Open spawn nemo

hc keybind XF86Display spawn ~/bin/rescreen
hc keybind XF86MonBrightnessDown spawn xbacklight -dec 5
hc keybind XF86MonBrightnessUp spawn xbacklight -inc 5
hc keybind XF86AudioRaiseVolume spawn pamixer -i 5
hc keybind XF86AudioLowerVolume spawn pamixer -d 5
hc keybind XF86AudioMute spawn pamixer -t

# tags
TAG_NAMES=( '1' '2' '3' '4' '5' '6' 'mail' 'irc' 'chat' )
hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
    hc add "${TAG_NAMES[$i]}"
done

# cycle through tags
hc keybind $Mod-Control-Right use_index +1 --skip-visible
hc keybind $Mod-Control-Left  use_index -1 --skip-visible
hc keybind $Mod-Control-Up    use_index -3 --skip-visible
hc keybind $Mod-Control-Down  use_index +3 --skip-visible
hc keybind $Mod-Shift-Control-Right move_index +1 --skip-visible
hc keybind $Mod-Shift-Control-Left  move_index -1 --skip-visible
hc keybind $Mod-Shift-Control-Up    move_index -3 --skip-visible
hc keybind $Mod-Shift-Control-Down  move_index +3 --skip-visible
hc keybind $Mod-bracketright move_index +1
hc keybind $Mod-bracketleft  move_index -1

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-u split vertical 0.5
hc keybind $Mod-o split horizontal 0.5
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# resizing
RESIZESTEP=0.05
hc keybind $Mod-Control-h resize left +$RESIZESTEP
hc keybind $Mod-Control-j resize down +$RESIZESTEP
hc keybind $Mod-Control-k resize up +$RESIZESTEP
hc keybind $Mod-Control-l resize right +$RESIZESTEP

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 resize
hc mousebind $Mod-Button3 zoom

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Shift-BackSpace   use $(herbstclient list_monitors | grep -v FOCUS | cut --delimiter='"' -f 2)
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right
hc keybind $Mod-i jumpto urgent
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

# colors
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'
hc set frame_bg_transparent 1
hc set frame_border_width 1
hc set window_border_width 2
hc set window_border_inner_width 1
hc set window_border_normal_color '#454545'
hc set window_border_active_color '#9fbc00'
hc set always_show_frame 1
hc set frame_gap 1
# add overlapping window borders
hc set window_gap -2
hc set frame_padding 2
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0


# rules
hc unrule -F
hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm.*|Konsole)' focus=on
hc rule class~'(Bpython2?(-gtk)?)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off
hc rule class=Firefox tag=1
hc rule class=Steam tag=3
hc rule class=Hexchat tag=irc
hc rule class=Thunderbird tag=mail
hc load chat '(split horizontal:0.150000:0
    (clients grid:0)
    (split horizontal:0.250000:0 (clients vertical:0) (clients vertical:0)))'
hc rule class=Pidgin tag=chat index=10
hc rule class~'(Gpodder|Audacious)' tag=chat index=11

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel2.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    $panel $monitor &
done
# Autostart some programs
pgrep xscreensaver || xscreensaver -nosplash &
pgrep dropbox || dropboxd || dropbox start &
pgrep nm-applet || nm-applet &
pgrep redshift || redshift &
pgrep dunst || dunst &
# Fix for Java AWT applets on non-reparenting WMs.
hc setenv _JAVA_AWT_WM_NONREPARENTING 1
